backend:
  name: git-gateway
  branch: main

# SEO 관련 설정 추가
enableRobotsTXT: true

sitemap:
  changefreq: "weekly"
  filename: "sitemap.xml"
  priority: 0.5  

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

locale: 'ko'

collections:
  - name: "web-posts"
    label: "웹 작업물"
    folder: "content/posts/web"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "소제목", name: "subtitle", widget: "string", required: false}
      - {label: "발행일", name: "date", widget: "datetime"}
      - {label: "이미지", name: "images", widget: "list", field: {label: "이미지", name: "image", widget: "image"}, required: false}
      - {label: "서브 카테고리", name: "subCategory", widget: "select", options: ["홈페이지 디자인", "디지털배너 디자인", "상세페이지 디자인", "UX/UI 디자인"], required: false}
      - {label: "태그", name: "tags", widget: "select", multiple: true, options: ["홈페이지 디자인", "디지털 배너 디자인", "상세페이지 디자인", "UX/UI 디자인", "카드뉴스 디자인", "포스터 디자인", "SNS광고 디자인", "로고 디자인", "브랜딩", "게임 광고 디자인", "인터넷 방송 디자인", "영상 제작", "영상 편집", "모션 그래픽", "유튜브 썸네일", "프론트엔드", "웹 퍼블리싱", "모바일 앱", "게임 개발", "현수막/엑스배너 디자인", "명함 디자인", "브로슈어/카탈로그 디자인", "광고매체 디자인", "패키지 디자인", "XD", "Photoshop", "Illustrator", "After Effects", "Premiere Pro", "Cinema 4D", "HTML5", "CSS3", "JavaScript", "Hugo", "Unity", "InDesign"], hint: "프로젝트와 관련된 스킬이나 작업 유형을 선택하세요", required: false}
      - {label: "카테고리", name: "categories", widget: "hidden", default: ["web"]}
      - {label: "내용", name: "body", widget: "markdown", editor_components: ["image"], hint: "본문에서도 이미지 업로드가 가능합니다. 위의 이미지 필드와 본문 이미지를 함께 활용하세요."}

  - name: "ad-posts"
    label: "광고 작업물"
    folder: "content/posts/ad"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "소제목", name: "subtitle", widget: "string", required: false}
      - {label: "발행일", name: "date", widget: "datetime"}
      - {label: "이미지", name: "images", widget: "list", field: {label: "이미지", name: "image", widget: "image"}, required: false}
      - {label: "서브 카테고리", name: "subCategory", widget: "select", options: ["현수막/엑스배너 디자인", "명함 디자인", "브로슈어/카탈로그 디자인", "광고매체 디자인", "패키지 디자인"], required: false}
      - {label: "태그", name: "tags", widget: "select", multiple: true, options: ["홈페이지 디자인", "디지털 배너 디자인", "상세페이지 디자인", "UX/UI 디자인", "카드뉴스 디자인", "포스터 디자인", "SNS광고 디자인", "로고 디자인", "브랜딩", "게임 광고 디자인", "인터넷 방송 디자인", "영상 제작", "영상 편집", "모션 그래픽", "유튜브 썸네일", "프론트엔드", "웹 퍼블리싱", "모바일 앱", "게임 개발", "현수막/엑스배너 디자인", "명함 디자인", "브로슈어/카탈로그 디자인", "광고매체 디자인", "패키지 디자인", "XD", "Photoshop", "Illustrator", "After Effects", "Premiere Pro", "Cinema 4D", "HTML5", "CSS3", "JavaScript", "Hugo", "Unity", "InDesign"], hint: "프로젝트와 관련된 스킬이나 작업 유형을 선택하세요", required: false}
      - {label: "카테고리", name: "categories", widget: "hidden", default: ["ad"]}
      - {label: "내용", name: "body", widget: "markdown", editor_components: ["image"], hint: "본문에서도 이미지 업로드가 가능합니다. 위의 이미지 필드와 본문 이미지를 함께 활용하세요."}

  - name: "content-posts"
    label: "콘텐츠 작업물"
    folder: "content/posts/content"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "소제목", name: "subtitle", widget: "string", required: false}
      - {label: "발행일", name: "date", widget: "datetime"}
      - {label: "이미지", name: "images", widget: "list", field: {label: "이미지", name: "image", widget: "image"}, required: false}
      - {label: "서브 카테고리", name: "subCategory", widget: "select", options: ["카드뉴스 디자인", "포스터 디자인", "SNS 광고"], required: false}
      - {label: "태그", name: "tags", widget: "select", multiple: true, options: ["홈페이지 디자인", "디지털 배너 디자인", "상세페이지 디자인", "UX/UI 디자인", "카드뉴스 디자인", "포스터 디자인", "SNS광고 디자인", "로고 디자인", "브랜딩", "게임 광고 디자인", "인터넷 방송 디자인", "영상 제작", "영상 편집", "모션 그래픽", "유튜브 썸네일", "프론트엔드", "웹 퍼블리싱", "모바일 앱", "게임 개발", "현수막/엑스배너 디자인", "명함 디자인", "브로슈어/카탈로그 디자인", "광고매체 디자인", "패키지 디자인", "XD", "Photoshop", "Illustrator", "After Effects", "Premiere Pro", "Cinema 4D", "HTML5", "CSS3", "JavaScript", "Hugo", "Unity", "InDesign"], hint: "프로젝트와 관련된 스킬이나 작업 유형을 선택하세요", required: false}
      - {label: "카테고리", name: "categories", widget: "hidden", default: ["content"]}
      - {label: "내용", name: "body", widget: "markdown", editor_components: ["image"], hint: "본문에서도 이미지 업로드가 가능합니다. 위의 이미지 필드와 본문 이미지를 함께 활용하세요."}

  - name: "creative-posts"
    label: "크리에이티브 작업물"
    folder: "content/posts/creative"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "소제목", name: "subtitle", widget: "string", required: false}
      - {label: "발행일", name: "date", widget: "datetime"}
      - {label: "이미지", name: "images", widget: "list", field: {label: "이미지", name: "image", widget: "image"}, required: false}
      - {label: "서브 카테고리", name: "subCategory", widget: "select", options: ["로고 디자인", "브랜딩", "게임 광고 디자인", "인터넷 방송 디자인"], required: false}
      - {label: "태그", name: "tags", widget: "select", multiple: true, options: ["홈페이지 디자인", "디지털 배너 디자인", "상세페이지 디자인", "UX/UI 디자인", "카드뉴스 디자인", "포스터 디자인", "SNS광고 디자인", "로고 디자인", "브랜딩", "게임 광고 디자인", "인터넷 방송 디자인", "영상 제작", "영상 편집", "모션 그래픽", "유튜브 썸네일", "프론트엔드", "웹 퍼블리싱", "모바일 앱", "게임 개발", "현수막/엑스배너 디자인", "명함 디자인", "브로슈어/카탈로그 디자인", "광고매체 디자인", "패키지 디자인", "XD", "Photoshop", "Illustrator", "After Effects", "Premiere Pro", "Cinema 4D", "HTML5", "CSS3", "JavaScript", "Hugo", "Unity", "InDesign"], hint: "프로젝트와 관련된 스킬이나 작업 유형을 선택하세요", required: false}
      - {label: "카테고리", name: "categories", widget: "hidden", default: ["creative"]}
      - {label: "내용", name: "body", widget: "markdown", editor_components: ["image"], hint: "본문에서도 이미지 업로드가 가능합니다. 위의 이미지 필드와 본문 이미지를 함께 활용하세요."}

  - name: "programming-posts"
    label: "프로그래밍 작업물"
    folder: "content/posts/programming"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "소제목", name: "subtitle", widget: "string", required: false}
      - {label: "발행일", name: "date", widget: "datetime"}
      - {label: "이미지", name: "images", widget: "list", field: {label: "이미지", name: "image", widget: "image"}, required: false}
      - {label: "서브 카테고리", name: "subCategory", widget: "select", options: ["프론트엔드", "웹 퍼블리싱", "모바일 앱", "게임 개발"], required: false}
      - {label: "태그", name: "tags", widget: "select", multiple: true, options: ["홈페이지 디자인", "디지털 배너 디자인", "상세페이지 디자인", "UX/UI 디자인", "카드뉴스 디자인", "포스터 디자인", "SNS광고 디자인", "로고 디자인", "브랜딩", "게임 광고 디자인", "인터넷 방송 디자인", "영상 제작", "영상 편집", "모션 그래픽", "유튜브 썸네일", "프론트엔드", "웹 퍼블리싱", "모바일 앱", "게임 개발", "현수막/엑스배너 디자인", "명함 디자인", "브로슈어/카탈로그 디자인", "광고매체 디자인", "패키지 디자인", "XD", "Photoshop", "Illustrator", "After Effects", "Premiere Pro", "Cinema 4D", "HTML5", "CSS3", "JavaScript", "Hugo", "Unity", "InDesign"], hint: "프로젝트와 관련된 스킬이나 작업 유형을 선택하세요", required: false}
      - label: "웹 데모 코드"
        name: "demoCode"
        widget: "code"
        default_language: "html"
        allow_language_selection: false
        hint: "프론트엔드/퍼블리싱 작업물의 경우 HTML+CSS 코드를 입력하면 라이브 데모가 표시됩니다"
        required: false
      - {label: "카테고리", name: "categories", widget: "hidden", default: ["programming"]}
      - {label: "내용", name: "body", widget: "markdown", editor_components: ["image"], hint: "본문에서도 이미지 업로드가 가능합니다. 위의 이미지 필드와 본문 이미지를 함께 활용하세요."}

  - name: "video-posts"
    label: "영상 작업물"
    folder: "content/posts/video"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "소제목", name: "subtitle", widget: "string", required: false}
      - {label: "발행일", name: "date", widget: "datetime"}
      - {label: "동영상 URL", name: "videoUrl", widget: "string", hint: "YouTube 또는 Vimeo URL을 입력하세요", required: false}
      - {label: "이미지", name: "images", widget: "list", field: {label: "이미지", name: "image", widget: "image"}, required: false}
      - {label: "서브 카테고리", name: "subCategory", widget: "select", options: ["영상 제작", "영상 편집", "모션그래픽", "유튜브 썸네일"], required: false}
      - {label: "태그", name: "tags", widget: "select", multiple: true, options: ["홈페이지 디자인", "디지털 배너 디자인", "상세페이지 디자인", "UX/UI 디자인", "카드뉴스 디자인", "포스터 디자인", "SNS광고 디자인", "로고 디자인", "브랜딩", "게임 광고 디자인", "인터넷 방송 디자인", "영상 제작", "영상 편집", "모션 그래픽", "유튜브 썸네일", "프론트엔드", "웹 퍼블리싱", "모바일 앱", "게임 개발", "현수막/엑스배너 디자인", "명함 디자인", "브로슈어/카탈로그 디자인", "광고매체 디자인", "패키지 디자인", "XD", "Photoshop", "Illustrator", "After Effects", "Premiere Pro", "Cinema 4D", "HTML5", "CSS3", "JavaScript", "Hugo", "Unity", "InDesign"], hint: "프로젝트와 관련된 스킬이나 작업 유형을 선택하세요", required: false}
      - {label: "카테고리", name: "categories", widget: "hidden", default: ["video"]}
      - {label: "내용", name: "body", widget: "markdown", editor_components: ["image"], hint: "본문에서도 이미지 업로드가 가능합니다. 위의 이미지 필드와 본문 이미지를 함께 활용하세요."}

  - name: "project-posts"
    label: "프로젝트 작업물"
    folder: "content/posts/project"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "소제목", name: "subtitle", widget: "string", required: false}
      - {label: "발행일", name: "date", widget: "datetime"}
      - {label: "이미지", name: "images", widget: "list", field: {label: "이미지", name: "image", widget: "image"}, required: false}
       
      - {label: "태그", name: "tags", widget: "select", multiple: true, options: ["홈페이지 디자인", "디지털 배너 디자인", "상세페이지 디자인", "UX/UI 디자인", "카드뉴스 디자인", "포스터 디자인", "SNS광고 디자인", "로고 디자인", "브랜딩", "게임 광고 디자인", "인터넷 방송 디자인", "영상 제작", "영상 편집", "모션 그래픽", "유튜브 썸네일", "프론트엔드", "웹 퍼블리싱", "모바일 앱", "게임 개발", "현수막/엑스배너 디자인", "명함 디자인", "브로슈어/카탈로그 디자인", "광고매체 디자인", "패키지 디자인", "XD", "Photoshop", "Illustrator", "After Effects", "Premiere Pro", "Cinema 4D", "HTML5", "CSS3", "JavaScript", "Hugo", "Unity", "InDesign"], hint: "프로젝트와 관련된 스킬이나 작업 유형을 선택하세요", required: false}
      - {label: "프로젝트 설명", name: "description", widget: "text", hint: "프로젝트에 대한 간단한 설명을 입력하세요", required: false}
      - {label: "카테고리", name: "categories", widget: "hidden", default: ["project"]}
      - {label: "내용", name: "body", widget: "markdown", editor_components: ["image"], hint: "본문에서도 이미지 업로드가 가능합니다. 위의 이미지 필드와 본문 이미지를 함께 활용하세요."}

  - name: "news"
    label: "소식 게시글"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "발행일", name: "date", widget: "datetime"}
      - {label: "이미지", name: "images", widget: "list", field: {label: "이미지", name: "image", widget: "image"}, required: false}
      - {label: "내용", name: "body", widget: "markdown", editor_components: ["image"], hint: "본문에서도 이미지 업로드가 가능합니다. 위의 이미지 필드와 본문 이미지를 함께 활용하세요."}